admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
