# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    dms_twig_extension.fabpot.intl.class: Twig_Extensions_Extension_Intl

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    dms_twig_extension.fabpot.intl:
        class: %dms_twig_extension.fabpot.intl.class%
        tags:
            - { name: twig.extension }